### PR TITLE
Update metadata before 1.4.8 release

### PR DESCRIPTION
**Pull request by ni-jfitzger**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
- [ ] ~I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~
- [ ] ~I've added tests applicable for this pull request~

### What does this Pull Request accomplish?
Update metadata to latest 24.3 export for most APIs.
Not Updated:
- nifgen is being updated in a separate PR
- niswitch had an unintended breaking change which I have an internal PR to fix, but I won't hold up the release for it

Resulting Changes:
* nidcpower has some documentation changes (mostly/all? just deletion of the word 'output')
* nidmm: `cal_type_raw` was changed to `cal_type` in _grpc_stub_interpreter.py
* Several apis had the order of things changed in their .proto files and the resulting generated files
  * If there were other changes, it's virtually impossible to tell, but our tests are passing
* The order of some imports changed in nifake

No new functions, properties, enums, classes, structs were added to any of the APIs

### List issues fixed by this Pull Request below, if any.
None

### What testing has been done?
PR Checks

### CODE REVIEW

**Comment by marcoskirsch** [comment]
Don't we usually add something like "API parity with NI-Digital Pattern Driver 2x.0.0." to the CHANGELOG in these PRs?

**Comment by ni-jfitzger** [comment]
> Don't we usually add something like "API parity with NI-Digital Pattern Driver 2x.0.0." to the CHANGELOG in these PRs?

There's only evidence of us doing that when we add new functions, properties, enums, etc for API parity. This PR includes no user-visible API changes. I'm not sure what's going on with that NI-DMM grpc change, but we test both of those functions and the tests passed.

**Comment by ni-jfitzger** [comment]
> Please confirm if this should include CHANGELOG changes. Should only be mentioned where the API changes are actually visible.

There is nothing that warrants touching the changelog.

**Review by tobiasgordon — APPROVED** [review]
This all looks fine to me.

**Pull request merged**
