### PR TITLE
Changes to fix and validate Travis-CI integration

### LINKED ISSUE #1633: travis-ci not running on PRs
### Description of issue

travis-ci didn't run on these comp;leted PRs:
 - https://github.com/ni/nimi-python/pull/1621
 - https://github.com/ni/nimi-python/pull/1624
 
It's also not running on these open PRs:
 - https://github.com/ni/nimi-python/pull/1631
 - https://github.com/ni/nimi-python/pull/1632

### PR DESCRIPTION
**Pull request by sbethur**
~- [ ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).~

~- [ ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~

~- [ ] I've added tests applicable for this pull request~

### What does this Pull Request accomplish?

Random changes to fix #1633 and validate the integration. DO NOT MERGE CHANGES.

### List issues fixed by this Pull Request below, if any.

* Fix #1633 

### What testing has been done?

PR build

### CODE REVIEW

**Comment by sbethur** [comment]
That didn't work.. I'm working with `ni` org GitHub admins to migrate to travis-ci.com

**Comment by sbethur** [comment]
ok to test

**Comment by sbethur** [comment]
test this please

**Comment by marcoskirsch** [comment]
> test this please

This re-triggers nimi-bot but not Travis-CI. I think you need to push a change.

**Comment by sbethur** [comment]
> 
> 
> > test this please
> 
> This re-triggers nimi-bot but not Travis-CI. I think you need to push a change.

Pushed 🤞

**Comment by marcoskirsch** [comment]
Travis CI caught a problem!

```python
import pytest
1740^
1741src/nidcpower/system_tests/test_system_nidcpower.py:4:1: H306: imports not in alphabetical order (pytest, hightime)
1742import hightime
1743^
1744ERROR: InvocationError for command /home/travis/build/ni/nimi-python/.tox/64/py38-flake8/bin/flake8 --config=./tox.ini src/nidcpower/system_tests/ src/nidcpower/examples/ (exited with code 1)
1745
```
It works! 

That was fixed in #1632. I think we're safe to close this now.

**Pull request closed without merging**
