### PR TITLE
Release 1.4.7

### PR DESCRIPTION
**Pull request by ni-jfitzger**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
- [X] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.
- ~[ ] I've added tests applicable for this pull request~

### What does this Pull Request accomplish?
Release 1.4.7. See CHANGELOG.md for list of changes.

### List issues fixed by this Pull Request below, if any.
None

### What testing has been done?
PR Checks

### CODE REVIEW

**Comment by ni-jfitzger** [comment]
With the latest dependencies, we're now failing `build_test` flake8 checks. I'll fix it in a separate PR.

**Comment by ni-jfitzger** [comment]
This change is blocked until #2034 goes in and is merged to the PR branch.

**Comment by ni-jfitzger** [comment]
This should not be merged until after 1.4.7 is released.

**Review by marcoskirsch — APPROVED** [review]

**Comment by ni-jfitzger** [comment]
The system test checks ran previously.
#2034 didn't affect code generation, really, just unit and and system tests and its checks completed fine.
Travis CI already passed for 3.11, so I won't wait on the other checks to merge.

**Pull request merged**
