### PR TITLE
Delete nidigital_do_nothing example

### LINKED ISSUE #1073: Need nidigital examples
* Description of issue

Need nidigital examples

### PR DESCRIPTION
**Pull request by ni-jxie**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).

~- [ ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~

~- [ ] I've added tests applicable for this pull request.~

### What does this Pull Request accomplish?

Delete nidigital_do_nothing.py example since we are adding real nidigital examples 

### List issues fixed by this Pull Request below, if any.

* Fix #1073

### CODE REVIEW

**Comment by ni-jxie** [comment]
It seems like after deleting the do_nothing example causes the examples folder to go away which makes the build process not happy. This should be remedied once any of the new example is merged into main.

**Comment by sbethur** [comment]
> It seems like after deleting the do_nothing example causes the examples folder to go away which makes the build process not happy. This should be remedied once any of the new example is merged into main.

I'll wait until one real example is submitted before reviewing this.

**Comment by sbethur** [comment]
@ni-jxie, can you please resolve the conflicts on this PR.

**Review by sbethur — APPROVED** [review]

**Comment by ni-jxie** [comment]
Yeah, it needs a rebase. Done.

**Comment by sbethur** [comment]
test this please

**Comment by ni-jxie** [comment]
@marcoskirsch Are you going to taking a look at this?

**Comment by sbethur** [comment]
ok to test

**Review by marcoskirsch — APPROVED** [review]

**Comment by marcoskirsch** [comment]
please resolve conflict, should be a codegen away

**Comment by ni-jxie** [comment]
@marcoskirsch rebase again, should be good to go.

**Pull request merged**
