### PR TITLE
Add support for repeated capabilities on methods that support independent channels

### PR DESCRIPTION
**Pull request by ni-erikcrank**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
- [ ]~I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~
- [ ]~I've added tests applicable for this pull request~

The repeated capabilities functionality of attributes and methods will be tested after independent channels session constructor is implemented. System tests will be added as part of this [Azure DevOps work item](https://ni.visualstudio.com/DevCentral/_workitems/edit/1413727). 

### What does this Pull Request accomplish?

Adds repeated capabilities to methods that support independent channels.

### What testing has been done?

Verified that DCPower system tests pass.

### CODE REVIEW

**Comment by sbethur** [comment]
ok to test

**Comment by sbethur** [comment]
We need system tests to validate calling the updated entry points with rep caps. Please add a link or work item number in which that will be done.

**Review by sbethur — APPROVED** [review]

**Review by marcoskirsch — APPROVED** [review]

**Comment by marcoskirsch** [comment]
@ni-erikcrank please re-run codegen and we'll merge.

**Comment by marcoskirsch** [comment]
>We need system tests to validate calling the updated entry points with rep caps. Please add a link or work item number in which that will be done.

Why not in the same PR?

**Review by marcoskirsch — CHANGES_REQUESTED** [review]
Awaiting system test changes

**Comment by ni-erikcrank** [comment]
System tests would not succeed until we have a constructor that allows creation of sessions with independent channels. I didn't want to submit failing system tests.

**Comment by marcoskirsch** [comment]
>System tests would not succeed until we have a constructor that allows creation of sessions with independent channels. I didn't want to submit failing system tests.

I think they would, if you pass something equivalent to "all the channels in the session" such as `""` or something else. Nevertheless, as long as you have the Issue to remind us to do it in a cleaner manner, that's fine with me.

**Comment by ni-erikcrank** [comment]
Let me know if you are still awaiting changes/actions from me.

**Comment by sbethur** [comment]
> Let me know if you are still awaiting changes/actions from me.

There are merge conflicts you need to resolve.

**Pull request merged**
