### PR TITLE
Faster Array Allocation

### LINKED ISSUE #1998: nimi-python APIs inefficiently allocate Python arrays
### Description of issue

Our code is using a pattern like the following:
`waveform_array_array = array.array("d", [0] * waveform_array_size)`

While discussing #1997 , we discovered that it's much more efficent to allocate the array as follows (especially for large arrays):
`waveform_array_array = array.array("d", [0]) * waveform_array_size`

We should update all array allocations in the repo to follow this pattern. This affects multiple APIs.

### PR DESCRIPTION
**Pull request by ni-jfitzger**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
- [X] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.
- ~[ ] I've added tests applicable for this pull request~

### What does this Pull Request accomplish?
When allocating a buffer, nimi-python APIs create a list of 0s then copy them into an array.array that is being initialized, causing allocation of the array to take much longer than necessary. For large buffers, the extra time spent allocating and copying the list is significant.

This change updates the allocation process to instead create a single element list `[0]` that is copied into the array, then use the `*` operator to extend the array to a specified number of elements.

### List issues fixed by this Pull Request below, if any.

* Fix #1998

### What testing has been done?

Functional: System and Unit tests
Performance: 
1. Tested allocation time of arrays of various sizes with both methods. When allocation time was not negligible (0 s measured), the new method consistently allocated faster, typically with a reduction in execution time of %90 or more.
3. With a real 5164 and NI-SCOPE 23.8.0 (in-dev version), tested `niscope.Session.fetch()` performance of single channel fetches of various record lengths and numbers of records.

100 Samples
niscope 1.4.5 fetch time: 0.002000
PR                  fetch time: 0.000999

10k Samples
niscope 1.4.5 fetch time: 0.001999
PR                  fetch time: 0.001987

1M Samples
niscope 1.4.5 fetch time: 0.051974
PR                  fetch time: 0.006997

100M Samples
niscope 1.4.5 fetch time: 5.340731
PR                  fetch time: 0.582741

10k Samples, 1k Records
niscope 1.4.5 fetch time: 0.589767
PR                  fetch time: 0.139914

1M Samples, 100 Records
niscope 1.4.5 fetch time: 5.240911
PR                  fetch time: 0.526281

100M Samples, 10 Records
niscope 1.4.5 fetch time: 5.177619
PR                  fetch time: 0.493325

### CODE REVIEW

**Comment by ni-jfitzger** [comment]
I didn't touch code where we were initializing an array with actual data.

**Comment by ni-jfitzger** [comment]
I noticed in `src\nidigital\templates\session.py\fancy_write_source_waveform_site_unique.py.mako` that we for some reason move data from a numpy array into an array.array. Why would we do that? Are numpy arrays just not compatible with that driver entrypoint.

**Comment by marcoskirsch** [comment]
> I noticed in src\nidigital\templates\session.py\fancy_write_source_waveform_site_unique.py.mako that we for some reason move data from a numpy array into an array.array. Why would we do that? Are numpy arrays just not compatible with that driver entrypoint?

The driver just cares that it is a big-enough contiguous block of memory. So it should be fine.

**Comment by marcoskirsch** [comment]
> I didn't touch code where we were initializing an array with actual data.

What is an example of that?

**Comment by ni-jfitzger** [comment]
> > I didn't touch code where we were initializing an array with actual data.
> 
> What is an example of that?

https://github.com/ni/nimi-python/blob/9b5cc3a38151fc76fafd024c3bbcc19f5864d14d/src/nidigital/templates/session.py/fancy_write_source_waveform_site_unique.py.mako#L32C64-L32C64

**Comment by bkeryan** [comment]
> > I noticed in src\nidigital\templates\session.py\fancy_write_source_waveform_site_unique.py.mako that we for some reason move data from a numpy array into an array.array. Why would we do that? Are numpy arrays just not compatible with that driver entrypoint?
> 
> The driver just cares that it is a big-enough contiguous block of memory. So it should be fine.

It's the contiguous part that requires copying. If the driver API accepted a separate buffer for each site, then it would make sense to pass numpy arrays to the driver API without copying.

**Review by marcoskirsch — APPROVED** [review]

**Pull request merged**
