### PR TITLE
Adding unit test for multipoint read

### PR DESCRIPTION
**Pull request by bhaswath**
[X ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/<reponame>/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?
Adds Unit test to NI-FAKE to test proper functionality of read_multipoint()
Modifies mock_helper.py so that read_multipoint() returns an array and not a float.

### Why should this Pull Request be merged?
Increases coverage

### What testing has been done?
Unit test passes locally

### CODE REVIEW

**Comment by bhaswath** [comment]
assert measurements == test_reading_array would cause an AssertionError to raise.
The value being returned is always an array of size test_actual_number_of_points,  but the values returned in the array are always 0.0
Is there any additional file that I must modify in order for this to return the values I expect it to?

**Comment by bhaswath** [comment]
How do I modify the mock_helper in bin?
I have changed mock_helper in generated.

**Comment by marcoskirsch** [comment]
> How do I modify the mock_helper in bin?

This file is code-generated. You should never modify it directly. It even says so in its first line:

`# This file was generated`

The file you should be modifying is:
build/templates/mock_helper.py.mako

**Comment by Fladolcetta** [comment]
Validated that multi_point read is already unit tests in the latest export of master.

https://raw.githubusercontent.com/ni/nimi-python/master/src/nifake/tests/test_session.py

**Pull request closed without merging**
