### PR TITLE
Fix style error

### PR DESCRIPTION
**Pull request by luisgomes252**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
- [ ] ~~I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~~
- [ ] ~~I've added tests applicable for this pull request~~

### What does this Pull Request accomplish?

Fix flake8 error introduced in #1624

### CODE REVIEW

**Comment by sbethur** [comment]
ok to test

**Comment by sbethur** [comment]
This happened because travis-ci isn't getting triggered for PRs. Filed an issue - #1633.

**Review by sbethur — APPROVED** [review]

**Comment by marcoskirsch** [comment]
ok to test

**Comment by sbethur** [comment]
ok to test

**Pull request merged**
