### PR TITLE
Updated driver versions that nimi-python tests against due to updated runtimes in nimibot

### PR DESCRIPTION
**Pull request by mgallatin**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).

~~- [ ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~~

~~- [ ] I've added tests applicable for this pull request~~

### What does this Pull Request accomplish?

Updated the versions nimi-python is tested against due to updates to the driver runtimes in nimibot.

### What testing has been done?

nimibot has updated runtimes, this PR should use them.

### CODE REVIEW

**Review by ni-jfitzger — APPROVED** [review]

**Comment by marcoskirsch** [comment]
@mgallatin please look at the failing system tests, we need those working before merging.

**Comment by mgallatin** [comment]
> System tests are failing.

> @mgallatin please look at the failing system tests, we need those working before merging.

I agree, they seem to be related to the runtime upgrade of NI-SWITCH on nimibot, not this PR in particular.  I've already contacted @DavidCurtiss about it and he's looking at it.

**Comment by marcoskirsch** [comment]
We will downgrade NI-SWITCH since a potential issue was discovered on the latest release. 😳

**Comment by ni-jfitzger** [comment]
Looks good to me and the tests are now passing. I'll merge.

**Pull request merged**
