### PR TITLE
Generate initiate in _SessionBase class instead of Session class to handle repeated capabilities

### PR DESCRIPTION
**Pull request by ni-erikcrank**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
- [ ] ~I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~
- [ ] ~I've added tests applicable for this pull request~
System test for repeated capabilities will be added in a subsequent pull request. #1614 

### What does this Pull Request accomplish?

Makes initiate work on channel-based sessions.

### What testing has been done?
Ran dcpower system tests.

### CODE REVIEW

**Comment by sbethur** [comment]
ok to test

**Review by sbethur — CHANGES_REQUESTED** [review]
metadata change is missing from the PR.

**Comment by ni-erikcrank** [comment]
> 
> 
> metadata change is missing from the PR.

No metadata changes were required for this PR. The render_in_session_base setting was already being set correctly.
See discussion here: https://ni.visualstudio.com/DevCentral/_git/ni-central/pullrequest/166227

**Review by sbethur — APPROVED** [review]

**Comment by sbethur** [comment]
test this please

**Pull request merged**
