### PR TITLE
Expose NI-SCOPE calibration functions and make calibration functions consistent for NI-DMM.

### LINKED ISSUE #328: Implement __repr__() for all classes
Good practice
https://stackoverflow.com/questions/3627793/best-output-type-and-encoding-practices-for-repr-functions

### LINKED ISSUE #1462: `nidmm.Session.get_cal_date_and_time` and `get_last_cal_temp` is different from other nimi-python drivers
### Description of issue

`nidmm.Session.get_cal_date_and_time` and `get_last_cal_temp` are inconsistent with the rest of `nimi-python`.
Instead of one method that takes in an enum, we should have two methods for each: 
* `get_ext_cal_last_date_and_time` and `get_self_cal_last_date_and_time`.
* `get_ext_cal_last_temp` and `get_self_cal_last_temp`
Note - this inconsistency was inherited from the C/LabVIEW API.

### LINKED ISSUE #1463: niscope module does not expose calibration info functionality
The following functions exist in NI-SCOPE runtime and can be accessed through a regular (not calibration) session. Yet they are not exposed in `nimi-python`. Equivalent methods are exposed in `nimi-python` for other driver modules. 

* niScope_CalFetchDate
* niScope_CalFetchTemperature
* niScope_CalFetchCount
* ~~niScope_CalFetchMiscInfo~~ will be handled in #1464 

When adding to nimi-python, we should make sure they are exposed in a way that is consistent with the other drivers in order to allow duck-typing usage.

NI-SCOPE uses an enum to select between self/external/manufacturing. We probably would be ok exposing self/external only as separate methods like all the other APIs do.

### PR DESCRIPTION
**Pull request by shilohbeeler-NI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).

- [x] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.

- [x] I've added tests applicable for this pull request

### What does this Pull Request accomplish?

Exposed a number of calibration functions in the NI-SCOPE API. Added methods to NI-DMM to make fetching calibration datetime and temperature consistent with other modules. Implemented __repr__ for _RepeatedCapabilities (after much experimenting, it didn't make sense to have __repr__ anywhere else, as best as I could tell).

### List issues fixed by this Pull Request below, if any.

* Fix #328 
* Fix #1462 
* Fix #1463 (niScope_CalFetchCount has not been exposed.)

### What testing has been done?

All system tests have been run on the relevant modules and have passed.

### CODE REVIEW

**Comment by sbethur** [comment]
test this please

**Comment by sbethur** [comment]
Pull Request is fixing multiple issues. As per [best practices](https://google.github.io/eng-practices/review/developer/small-cls.html), we should strive for small bite-sized changes. Can you please split-up the PR.

**Comment by marcoskirsch** [comment]
> Implemented repr for _RepeatedCapabilities (after much experimenting, it didn't make sense to have repr anywhere else, as best as I could tell).

Please make this its own PR. Make PRs single-purpose and self-contained as much as it makes sense to.

**Comment by marcoskirsch** [comment]
Also looks like you have merge conflics and failing tests.

**Comment by shilohbeeler-NI** [comment]
Closing PR to investigate issues and separate into single-purpose PRs.

**Pull request closed without merging**
