### PR TITLE
Retire deprecated nimibot files

### PR DESCRIPTION
**Pull request by sbethur**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).

~- [ ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~

~- [ ] I've added tests applicable for this pull request~

### What does this Pull Request accomplish?

- Retire nimibot deployed on AzDO
- Delete files for AzDO variant of nimibot
- Delete files for Jenkins variant of nimibot

Going forward the one and only nimibot will be the one deployed using GitHub Actions.

### List issues fixed by this Pull Request below, if any.

None

### What testing has been done?

PR build

### CODE REVIEW

**Review by marcoskirsch — APPROVED** [review]
nimibot is dead.
Long live `nimibot`!

**Comment by SukruthGrandhiNI** [comment]
Need to update the wiki: https://github.com/ni/nimi-python/wiki/nimibot-System-Test-machine after this changes went in.

Should I clean up the nimibot related files in ni-central?
1. Delete the Azure related pipelines
https://ni.visualstudio.com/DevCentral/_build?definitionId=7820
https://ni.visualstudio.com/DevCentral/_build?definitionId=7821
https://ni.visualstudio.com/DevCentral/_build?definitionId=7650

2. Clean up the Packer template files
1. https://ni.visualstudio.com/DevCentral/_git/ni-central?path=/eng/iac/build/packer/templates/nimibot_win.json&version=GBmain&_a=contents
2. https://ni.visualstudio.com/DevCentral/_git/ni-central?path=/eng/iac/build/packer/templates/nimibot_rhel.json&version=GBmain&_a=contents


Also update the doc: https://dev.azure.com/ni/DevCentral/_wiki/wikis/AppCentral.wiki/23787/nimi-python

**Comment by SukruthGrandhiNI** [comment]
Also you can remove me from nimi-python module administrator.

**Review by SukruthGrandhiNI — APPROVED** [review]

**Comment by sbethur** [comment]
> Need to update the wiki: https://github.com/ni/nimi-python/wiki/nimibot-System-Test-machine after this changes went in.
> 
> Should I clean up the nimibot related files in ni-central?
> 
> Delete the Azure related pipelines
> 
>     1. https://ni.visualstudio.com/DevCentral/_build?definitionId=7820
> 
>     2. https://ni.visualstudio.com/DevCentral/_build?definitionId=7821
> 
>     3. https://ni.visualstudio.com/DevCentral/_build?definitionId=7650
> 
> 
> Clean up the Packer template files
> 
>     1. https://ni.visualstudio.com/DevCentral/_git/ni-central?path=/eng/iac/build/packer/templates/nimibot_win.json&version=GBmain&_a=contents
> 
>     2. https://ni.visualstudio.com/DevCentral/_git/ni-central?path=/eng/iac/build/packer/templates/nimibot_rhel.json&version=GBmain&_a=contents
> 
> 
> Update the doc: https://dev.azure.com/ni/DevCentral/_wiki/wikis/AppCentral.wiki/23787/nimi-python

@SukruthGrandhiNI, thanks for outlining the remaining work. I created an internal work item for tracking it: AB#2089539.

We'd appreciate your help in cleaning up the packer templates and documentation.

**Pull request merged**
