### PR TITLE
Update "Driver Version Tested Against" to 20.0.0

### PR DESCRIPTION
**Pull request by sbethur**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).

- [x] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.

~- [ ] I've added tests applicable for this pull request~

### What does this Pull Request accomplish?

Update "Driver Version Tested Against" to 20.0.0:
- 20.0.0 Driver Runtimes has been installed on nimi-bot
- Update applies to all modules except nidigital, whose latest released Runtime is 19.0.1

### List issues fixed by this Pull Request below, if any.

None

### What testing has been done?

CI will run the tests

### CODE REVIEW

**Comment by sbethur** [comment]
https://github.com/ni/nimi-python/pull/1460 created for niscope test failures.

**Comment by sbethur** [comment]
https://github.com/ni/nimi-python/pull/1461 created for nidcpower test failures

**Comment by marcoskirsch** [comment]
You can merge from master so that all tests pass prior to merging.

**Comment by sbethur** [comment]
test this please

**Pull request merged**
