### PR TITLE
Use unittest.mock instead of third-party mock library

### PR DESCRIPTION
**Pull request by sbethur**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).

~- [ ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~

~- [ ] I've added tests applicable for this pull request~

### What does this Pull Request accomplish?

Latest version of the flake8 plugin `hacking` added a check - `H216: The unittest.mock module should be used rather than the third party mock package unless actually needed.`

When I recreated my tox environment locally, I ran into this violation. The PR replaces third-party mock library with the built-in one.

### List issues fixed by this Pull Request below, if any.

N/a

### What testing has been done?

PR pipeline tests

### CODE REVIEW

**Review by marcoskirsch — APPROVED** [review]

**Comment by marcoskirsch** [comment]
Unit tests for `nidigital` fail.

**Comment by sbethur** [comment]
test this please

**Comment by sbethur** [comment]
Rebase went bad, retrying in #1687.

**Pull request closed without merging**
