### PR TITLE
Fix tests so they check for the right text type regardless of Python version

### LINKED ISSUE #565: nimodinst system tests fail on Python 2
On Python 2, getting a string attribute returns a unicode. On Python 3 it returns a str.
This is correct behavior from NI-ModInst, but the failing tests expect str.

```
Z:\>python -m pytest src\nimodinst\system_tests\
============================= test session starts =============================
platform win32 -- Python 2.7.13, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- C:\Python27\python.exe
cachedir: .cache
rootdir: Z:\, inifile: tox.ini
collected 15 items

src/nimodinst/system_tests/test_system_nimodinst.py::test_bad_device_family PASSED
src/nimodinst/system_tests/test_system_nimodinst.py::test_no_device_family PASSED
src/nimodinst/system_tests/test_system_nimodinst.py::test_device_family_string_with_dashes PASSED
src/nimodinst/system_tests/test_system_nimodinst.py::test_device_family_string_without_dashes PASSED
src/nimodinst/system_tests/test_system_nimodinst.py::test_int_attribute_error_on_non_existant_device PASSED
src/nimodinst/system_tests/test_system_nimodinst.py::test_string_attribute_error_on_non_existant_device PASSED
src/nimodinst/system_tests/test_system_nimodinst.py::test_device_name_attribute FAILED
src/nimodinst/system_tests/test_system_nimodinst.py::test_device_model_attribute FAILED
src/nimodinst/system_tests/test_system_nimodinst.py::test_serial_number_attribute FAILED
src/nimodinst/system_tests/test_system_nimodinst.py::test_bus_number_attribute PASSED
src/nimodinst/system_tests/test_system_nimodinst.py::test_chassis_number_attribute PASSED
src/nimodinst/system_tests/test_system_nimodinst.py::test_max_pciexpress_link_width_attribute PASSED
src/nimodinst/system_tests/test_system_nimodinst.py::test_pciexpress_link_width_attribute PASSED
src/nimodinst/system_tests/test_system_nimodinst.py::test_slot_number_attribute PASSED
src/nimodinst/system_tests/test_system_nimodinst.py::test_socket_number_attribute PASSED

================================== FAILURES ===================================
_________________________ test_device_name_attribute __________________________

    def test_device_name_attribute():
        with nimodinst.Session('') as session:
            assert len(session) > 0, 'Must have hardware for ModInst tests to be valid.'
>           assert isinstance(session[0].device_name, str)
E           AssertionError: assert False
E            +  where False = isinstance('PXI1Slot8', str)
E            +    where 'PXI1Slot8' = <nimodinst.session.Device object at 0x000000000439B4E0>.device_name

src\nimodinst\system_tests\test_system_nimodinst.py:52: AssertionError
_________________________ test_device_model_attribute _________________________

    def test_device_model_attribute():
        with nimodinst.Session('') as session:
            assert len(session) > 0, 'Must have hardware for ModInst tests to be valid.'
            assert len(session[0].device_model) > 0
>           assert isinstance(session[0].device_model, str)
E           AssertionError: assert False
E            +  where False = isinstance('NI PXIe-4145', str)
E            +    where 'NI PXIe-4145' = <nimodinst.session.Device object at 0x00000000043B2160>.device_model

src\nimodinst\system_tests\test_system_nimodinst.py:60: AssertionError
________________________ test_serial_number_attribute _________________________

    def test_serial_number_attribute():
        with nimodinst.Session('') as session:
            assert len(session) > 0, 'Must have hardware for ModInst tests to be valid.'
            pattern = r'^[0-9A-F]+$'
>           assert isinstance(session[0].serial_number, str)
E           AssertionError: assert False
E            +  where False = isinstance('0173C4F6', str)
E            +    where '0173C4F6' = <nimodinst.session.Device object at 0x00000000043AEA58>.serial_number

src\nimodinst\system_tests\test_system_nimodinst.py:69: AssertionError
===================== 3 failed, 12 passed in 0.93 seconds =====================

```

It's possible that other system tests have similar issues. #564 would catch that.
It's also a concern that we don't catch this in our unit tests.

### PR DESCRIPTION
**Pull request by marcoskirsch**
[x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).

~~[] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~~

[x] I've added any unit tests that are applicable for this pull request

### What does this Pull Request accomplish?

Use six module to check text type in our tests.

### List issues fixed by this Pull Request below, if any.

* Fix #565 

### What testing has been done?

Ran all tests

### CODE REVIEW

**Comment by texasaggie97** [comment]
You need to add six as a dependency in tox.ini so it will get installed.

**Comment by marcoskirsch** [comment]
> You need to add six as a dependency in tox.ini so it will get installed.

I figured that was going to be needed, but it worked on my local system so I figured I'd give it a shot on nimi-bot.

**Comment by marcoskirsch** [comment]
please test this

**Comment by marcoskirsch** [comment]
test this please

**Comment by marcoskirsch** [comment]
Ran into the dreaded:

```
E           niscope.errors.Error: -2147220735: MAX:  (Hex 0x80040301) Internal error: The specified class could not be found in the configuration database. Your installation may need to be repaired.
E           
E           Component Name: 
E           File Name: 
E           Line Number: 0
E           
E           Status Code: -2147220735

.tox\system_tests\lib\site-packages\niscope\errors.py:79: Error
```

**Comment by marcoskirsch** [comment]
MAX took forever to open on nimi-bot, only to show this:

screen shot 2017-11-05 at 8 40 18 pm

I'm rebooting nimi-bot but we may have again run into something more serious. May be time to have someone look into it.

**Comment by marcoskirsch** [comment]
test this please

**Comment by marcoskirsch** [comment]
Rebooting nimi-bot did the trick.

**Pull request merged**
