### PR TITLE
Update nimibot driver versions for 21.8 releases

### PR DESCRIPTION
**Pull request by mike-petersen-ni**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).

- [x] ~I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~

- [x] ~I've added tests applicable for this pull request~

### What does this Pull Request accomplish?

The [NI-FGEN][1] and [NI-DCPower][2] drivers have released 21.8 versions, as have their common dependencies of NI-ModInst and NI-TClk. The CI (nimibot) is currently being updated to use these newer versions, so that the builds and test results can be representative. As part of the update, the documentation and metadata should be updated accordingly.

[1]: <https://www.ni.com/en-us/support/downloads/drivers/download.ni-fgen.html>
[2]: <https://www.ni.com/en-us/support/downloads/drivers/download.ni-dcpower.html>

### What testing has been done?

Verified that similar changes were performed as in #1673 (the last time these versions were updated).

### CODE REVIEW

**Review by marcoskirsch — APPROVED** [review]

**Comment by sbethur** [comment]
@mike-petersen-ni, the [nimibot log](https://github.com/ni/nimi-python/runs/6113682257?check_suite_focus=true#step:3:36) says NI-DCPower Runtime version is 21.5. Something's not quite right.

**Review by sbethur — APPROVED** [review]

**Comment by sbethur** [comment]
> @mike-petersen-ni, the [nimibot log](https://github.com/ni/nimi-python/runs/6113682257?check_suite_focus=true#step:3:36) says NI-DCPower Runtime version is 21.5. Something's not quite right.

New PRs don't have this issue. I'm guessing the PRs created before the nimibot updates are still using the older image. This is ok, no need to change anything.

**Pull request merged**
