### PR TITLE
Read grpc_device_server port from any line of server output when running system_tests

### PR DESCRIPTION
**Pull request by ni-jfitzger**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
- ~[ ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~
- ~[ ] I've added tests applicable for this pull request~

### What does this Pull Request accomplish?
https://github.com/ni/grpc-device/pull/989 altered the output of grpc_device_server.exe and caused our internal nimi-python test suites to fail all gRPC tests. I discussed this with ni/grpc-device owners / contributors and it was determined there is no contract for the output to follow a certain format.

A copy of https://github.com/ni/nidaqmx-python/pull/450, this change updates GrpcServerProcess to keep reading the server output until the server port is parsed.

Note: this won't fix our internal ats failures until we release.

Alternatives:
I tried reading the port from the server json config instead, but it caused the tests to fail on nimibot. Not sure if this was due to running tests in parallel for different apis on the same VM at once or due to a difference with the version of grpc_device_server.exe in use.

### List issues fixed by this Pull Request below, if any.
Internal Bug [AB#2508876](https://dev.azure.com/ni/DevCentral/_workitems/edit/2508876) (once we release)

### What testing has been done?
Ran the niscope system tests without the breaking grpc-device change and with it. Tests passed in both cases.

### CODE REVIEW

**Comment by bkeryan** [comment]
This doesn't work when the port number is dynamically chosen. The configuration file specifies port 0 in this case.

MeasurementLink and nidaqmx-python also read the port number from stdout/stderr. I did not expect adding an unrelated line of output to break this.

**Comment by bkeryan** [comment]
MeasurementLink looks for a line of output matching `/Server listening on port (\d+)/` and should not be affected by this change.

nidaqmx-python has code that is copied from nimi-python, so it only looks at the first line of output: https://github.com/ni/nidaqmx-python/blob/master/tests/_grpc_utils.py

Cc: @zhindes

**Comment by bkeryan** [comment]
BTW, I realize the tests are using the default server configuration, which uses a hardcoded port. I have considered adding a config file for nidaqmx-python to use a dynamic port so that the tests don't fail if the server is already running with the default config, but I guess I didn't do anything about this.

**Comment by ni-jfitzger** [comment]
> BTW, I realize the tests are using the default server configuration, which uses a hardcoded port. I have considered adding a config file for nidaqmx-python to use a dynamic port so that the tests don't fail if the server is already running with the default config, but I guess I didn't do anything about this.

Yeah, we run the tests in a controlled setting where the server will not already be running with the default port. A person manually running the tests on their own system would have failures if the server was already running, but that's already the case. I'm not sure it's worth caring about.

**Comment by ni-jfitzger** [comment]
> > BTW, I realize the tests are using the default server configuration, which uses a hardcoded port. I have considered adding a config file for nidaqmx-python to use a dynamic port so that the tests don't fail if the server is already running with the default config, but I guess I didn't do anything about this.
> 
> Yeah, we run the tests in a controlled setting where the server will not already be running with the default port. A person manually running the tests on their own system would have failures if the server was already running, but that's already the case. I'm not sure it's worth caring about.

I spoke too soon. Our tests failed. Probably because we run a bunch of them in parallel.

**Comment by bkeryan** [comment]
> Yeah, we run the tests in a controlled setting where the server will not already be running with the default port. A person manually running the tests on their own system would have failures if the server was already running, but that's already the case. I'm not sure it's worth caring about.

I often ran into this with nidaqmx-python when working with examples and then running auto tests.

I've also written tests in NI internal components that bind to a hardcoded port, and these intermittently failed when run from build pipelines because *something* (possibly another instance of the same test) was using the port. Switching to a dynamic port made these tests more resilient.

Anyway, the behavior of the nimi-python tests is up to you, not me, but I wanted to share some reasons why I've considered changing that behavior for nidaqmx-python.

> I spoke too soon. Our tests failed. Probably because we run a bunch of them in parallel.

If you're using physical devices or persistent simulated devices, parallelizing tests isn't going to work even with a dynamic port, but if you're using persistent simulated devices, it could work.

**Comment by bkeryan** [comment]
Here is my proposed fix for nidaqmx-python: https://github.com/ni/nidaqmx-python/pull/450

**Review by marcoskirsch — APPROVED** [review]

**Pull request merged**
