### PR TITLE
Add unit tests and modified function_addon and mock helper for fixed and passed in functions.

### PR DESCRIPTION
**Pull request by injaleea**
[X] This contribution adheres to [CONTRIBUTING.md]

### What does this Pull Request accomplish?

Update functions_addon.py for fixed and passed in parameters
Updates mock helper to fix issues with string encoding and selecting the minimum size.
unit test for:
test_string_with_specified_buffer
test_string_with_fixed_buffer
test_returning_string_and_number

### Why should this Pull Request be merged?

More unit test coverage for nifake

tox paased on local machine

### CODE REVIEW

**Comment by marcoskirsch** [comment]
```
bin/nifake/nifake/tests/test_session.py::TestSession::test_set_vi_string_attribute FAILED
bin/nifake/nifake/tests/test_session.py::TestSession::test_string_with_specified_buffer FAILED
bin/nifake/nifake/tests/test_session.py::TestSession::test_string_with_fixed_buffer FAILED
bin/nifake/nifake/tests/test_session.py::TestSession::test_retunring_string_and_number FAILED
```

**Comment by injaleea** [comment]
All tests in PR is passing with python-2.7 after the updating function_addon to overwrite viChar to viString. But tests fails on python 3.6 

Waiting on Mark and Marcos to confirm on the internal logic regarding how we handle ViChar[] vs ViString.

**Comment by injaleea** [comment]
Removed 
- test_set_bool_attribute
- test_set_vi_string_attribute 
from this PR and created PR #412 since ViChar buffer issue is stopping this PR from merging .

**Comment by Fladolcetta** [comment]
This seems to be related to #392  and #396

**Comment by Fladolcetta** [comment]
This is currently failing, @texasaggie97 will be fixing failures for arrays to prevent encoding arrays.

**Comment by marcoskirsch** [comment]
@injaleea there are conflicts to resolve

**Pull request merged**
