### PR TITLE
Update product versions tested against windows nimibot created using IaC

### PR DESCRIPTION
**Pull request by SukruthGrandhiNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).

~~- [ ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~~

~~- [ ] I've added tests applicable for this pull request~~

### What does this Pull Request accomplish?
Update product versions tested against nimibot created using IaC.

Note: In RHEL only 4 products are installed, where as in Windows there are 7 products installed. Product versions which are installed on RHEL are as same as Windows.

 Windows Feeds: [link](https://ni.visualstudio.com/DevCentral/_git/ni-central?path=/eng/iac/cfg_mgmt/salt/srv/salt/nimibot/win/resources/driver_feeds_win.yml)
RHEL Feeds: [link](https://ni.visualstudio.com/DevCentral/_git/ni-central?path=/eng/iac/cfg_mgmt/salt/srv/salt/nimibot/rhel/resources/feeds_linux.yml)

### What testing has been done?
No testing done since it is a doc update

### CODE REVIEW

**Review by sbethur — CHANGES_REQUESTED** [review]
The change needs to be sourced from metadata. See https://github.com/ni/nimi-python/pull/1648/.

**Comment by sbethur** [comment]
The versions also match was we have on RHEL agent, right? If yes, please update the title and description to reflect that.

**Comment by SukruthGrandhiNI** [comment]
> The versions also match was we have on RHEL agent, right? If yes, please update the title and description to reflect that.

Not all the products are installed on the RHEL so I did not mention in the description.
Windows Feeds: [link](https://ni.visualstudio.com/DevCentral/_git/ni-central?path=/eng/iac/cfg_mgmt/salt/srv/salt/nimibot/win/resources/driver_feeds_win.yml)

RHEL Feeds: [link](https://ni.visualstudio.com/DevCentral/_git/ni-central?path=/eng/iac/cfg_mgmt/salt/srv/salt/nimibot/rhel/resources/feeds_linux.yml)

Whatever versions installed on RHEL are same of Windows.

**Comment by marcoskirsch** [comment]
Only two system tests ran on RHEL:

Screen Shot 2021-11-17 at 4 57 35 PM

I expected:

1. NI-DCPower
2. NI-DMM
3. NI-SCOPE
4. NI-SWITCH

nisimdev_path: //nirvana.natinst.com/perforceExports/build/exports/ni/nisi/nisimdev/official/export/21.3/21.3.0f119

**Review by marcoskirsch — CHANGES_REQUESTED** [review]
Waiting for metadata change.

**Comment by marcoskirsch** [comment]
@sbethur didn't we have a recently added check in place to confirm generated VS repo match?

**Comment by SukruthGrandhiNI** [comment]
> The change needs to be sourced from metadata. See #1648.

I missed this comment yesterday.  Done the changes

**Comment by SukruthGrandhiNI** [comment]
> Waiting for metadata change.

Changes are done.

**Comment by sbethur** [comment]
> 
> 
> @sbethur didn't we have a recently added check in place to confirm generated VS repo match?

It was considered but in the end didn't go in: https://github.com/ni/nimi-python/pull/1653#discussion_r715025154. The consensus was that Travis CI is the better place for it.

**Comment by marcoskirsch** [comment]
I remember now. Do we have a bug for adding it to TravisCI @sbethur ?

**Review by marcoskirsch — APPROVED** [review]

**Comment by sbethur** [comment]
> 
> 
> I remember now. Do we have a bug for adding it to TravisCI @sbethur ?

Just filed one - https://github.com/ni/nimi-python/issues/1674.

**Pull request merged**
