### PR TITLE
Update nidcpower sample code from modified example

### PR DESCRIPTION
**Pull request by luisgomes252**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
- [ ] ~~I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~~
- [ ] ~~I've added tests applicable for this pull request~~

### What does this Pull Request accomplish?

Updates the nidcpower sample code used in the readme to match the nidcpower_measure_record.py example updated [here](https://github.com/ni/nimi-python/pull/1600).

### CODE REVIEW

**Comment by sbethur** [comment]
ok to test

**Review by sbethur — APPROVED** [review]

**Comment by sbethur** [comment]
test this please

**Comment by marcoskirsch** [comment]
ok to test

**Review by marcoskirsch — APPROVED** [review]

**Comment by marcoskirsch** [comment]
ok to test

**Comment by sbethur** [comment]
System test failures in `niscope` and `niswitch` are due to infrastructure issues.

**Pull request merged**
